### ISSUE TITLE
Service Schedule field within 'edit sensor variables' doesn't allow for required time period

### ISSUE THREAD

**Issue by emmasteventon** [OceanOPS/web-dashboard#9]
**Context/Theme**
Keep applicable option(s):
-SOT

**Describe the bug**
A clear and concise description of what the bug is: No ability to enter '36 months' as a servicing schedule duration for a PTB110

**To Reproduce**
1. Go to 'edit sensor variable'
2. Click on 'service schedule'
4. See error - no option for 36 months

**Expected behavior**
We would want to be able to select any time period required

**Screenshots**
![image](https://user-images.githubusercontent.com/103102833/192484593-7eeda057-c535-4bd0-bb21-4cdef907b72b.png)

**Browsing information (please complete the following information):**

**Priority**
If blocking, please select the corresponding label.

**Additional context**

**Comment by anthoninlize** [comment]
Hi Emma,

By design, this has been restricted a preset list of values (I can't remember the discussion about it).
We would need to know if this field value would be rather similar in general (in which case we can add the missing value to the list, and maybe a few extra ones) or would it be completely heterogeneous (in which case, we need to update the way it is presented and stored)?

thanks

**Comment by emmasteventon** [comment]
Hi Antonin, 
I think perhaps the reference table linked to this field isn't the right one...
From the new SOT metadata format doc, the hyperlinked reference table is  the 'Time Period' - which is different to the one linked on the OceanOps interface. 
Looking back through to the TT-Meta ref-tables spreadsheet (https://wmoomm-my.sharepoint.com/:x:/g/personal/mkramp_wmo_int/EYyA-fASStVPuZNZJB9KCX8B9kV0FEYU3qejttsTxdN_oA?e=hbiXm3) it's not exactly clear what we agreed (and I can't remember either!) but I think we need to be able to select a 'number' and a 'unit' (i.e. day/month/year) in order to capture all the differing requirements. 

Is that possible?
many thanks, Emma

**Comment by anthoninlize** [comment]
The code table and what's used on the interface is the same, but the code table is missing 2 values.

Having a unit and number would be possible, but require some work on our side (database, UI).
We'll plan that then. It will be something similar to schedule of observation for the station :
![image](https://user-images.githubusercontent.com/17119571/193038624-986e58c5-67de-4c84-b7dc-e5f885d8ee9f.png)

**Comment by tomlatter** [comment]
Before making the change, I think we should ask confirmation from the team. It will complicate the user interface with 3 fields instead of one. A cleaner solution may be to add 10 or so more options to the list/time period ref table; It seems for service schedule these will only be in weeks or months. We can add options for 2 weeks, 3 weeks, 3 months, 4 months, 36 months, 48 months, etc.

**Comment by anthoninlize** [comment]
- [ ] add requested values to the list

- [ ] update exported reference tables
